name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build application
        run: |
          npm ci
          npm run build

      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          path: dist/
          remote_host: ${{ secrets.DROPLET_IP }}
          remote_user: ${{ secrets.DROPLET_USER }}
          remote_port: 22
          remote_path: /var/www/dog-in
          remote_key: ${{ secrets.DROPLET_SSH_KEY }}
          rsh: "ssh -o StrictHostKeyChecking=no"
